### ISSUE TITLE
.Net 9.0 Compatibility

### ISSUE THREAD

**Issue by sprehn-ero** [lkroliko/HealthCheck#1]
Nice work! We use this health check to avoid adding curl to all our containers.

When running version 8.0.0 on a .net 9.0 environment, e.g. mcr.microsoft.com/dotnet/aspnet:9.0-alpine, the call to healthckeck.dll will fail:

```
/app # dotnet healthcheck.dll http://localhost:8080/health
You must install or update .NET to run this application.

App: /app/healthcheck.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0' (x64)
.NET location: /usr/share/dotnet/

The following frameworks were found:
  9.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

It is possible to work around by specifying the roll forward policy major:

``` 
dotnet --roll-forward major healthcheck.dll http://localhost:8080/health
```

@lkroliko would you be so kind to publish a version compiled for 9.0?

**Comment by lkroliko** [comment]
Hello. I will make .net 9 support.
